#!/bin/bash
# Publish FD_TC_001..005 (Tiroshan FD_UAT) to INT — booking side + DDS pin.
# Artifacts are generated by scripts/generate_fd_tc_data.py.
#
# Prereqs (only you can do these):
#   1. aws sso login --profile ARC75-Temp-INT      (account 982081066747)
#   2. WARP / Cloudflare CONNECTED                  (private broker + endpoint DNS)
#
# Usage:
#   ./scripts/publish_fd_tc.sh --dry-run     # default: render only, prints what would run
#   ./scripts/publish_fd_tc.sh --live        # render + publish PNR + tickets + S3 + emit pin cmd
#
# Stages: 1 render → 2 publish PNR(INT) → 3 wait → 4 tickets → 5 DDS S3 PUT → 6 execution_traces pin
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
KB="$SCRIPT_DIR/.."
FD_SIT="$KB/scenarios/fd-sit"
DDS_DIR="$FD_SIT/_dds-templates"
AURORA_QUERY="$KB/../CCT_Agent_New/cct-cascade/contrail/_legacy/runner/plugins/aurora_query.py"

PROFILE="ARC75-Temp-INT"
REGION="ca-central-1"
PNR_TOPIC="emh-int.ALTEA-PNRDATA-INT"
INT_BROKERS="b-1.accctmskintcac1.z22bz6.c3.kafka.ca-central-1.amazonaws.com:9092,b-2.accctmskintcac1.z22bz6.c3.kafka.ca-central-1.amazonaws.com:9092,b-3.accctmskintcac1.z22bz6.c3.kafka.ca-central-1.amazonaws.com:9092"
S3_BUCKET="ac-cct-rule-engine-store-int"
RE_CLUSTER="ac-cct-rule-engine-platform-cluster-int"
DATE="2026-06-15"
TODAY="$(date -u +%Y-%m-%d)"
PNRS=(ZZTC01 ZZTC02 ZZTC03 ZZTC04 ZZTC05)

LIVE=false
[[ "${1:-}" == "--live" ]] && LIVE=true
echo "=== FD_TC publish — LIVE=$LIVE | profile=$PROFILE | topic=$PNR_TOPIC ==="

# ---- 0. regenerate artifacts (safe, local) --------------------------------
python3 "$SCRIPT_DIR/generate_fd_tc_data.py"

if [[ "$LIVE" == "true" ]]; then
  echo "--- preflight: aws identity ---"
  aws sts get-caller-identity --profile "$PROFILE" >/dev/null \
    || { echo "ERR: run 'aws sso login --profile $PROFILE' first"; exit 1; }
  nc -z -w3 "$(echo "$INT_BROKERS" | cut -d, -f1 | cut -d: -f1)" 9092 \
    || { echo "ERR: broker unreachable — is WARP connected?"; exit 1; }
fi

TMP="/tmp/fd-tc-$$"; mkdir -p "$TMP"

for pnr in "${PNRS[@]}"; do
  pnr_id="${pnr}-${DATE}"
  echo ""
  echo "########## $pnr_id ##########"

  # 1. render booking
  python3 "$SCRIPT_DIR/scenario_engine.py" render \
    --scenario "$FD_SIT/${pnr_id}.json" --out "$TMP/${pnr}.ndjson" >/dev/null
  echo "  [1] rendered booking ndjson"

  if [[ "$LIVE" == "true" ]]; then
    # 2. publish PNR to INT
    python3 "$SCRIPT_DIR/publish_raw.py" --ndjson "$TMP/${pnr}.ndjson" \
      --brokers "$INT_BROKERS" --topic "$PNR_TOPIC" --live 2>&1 | grep -Ei "produced|done" | head -1
    echo "  [2] published PNR -> $PNR_TOPIC"
  else
    echo "  [2] (dry-run) would publish -> $PNR_TOPIC"
  fi

  # 5. DDS S3 key
  uuid="$(python3 -c 'import uuid;print(uuid.uuid4())')"
  s3_key="traces/DDS/${TODAY}/${uuid}/response.json"
  if [[ "$LIVE" == "true" ]]; then
    aws s3 cp "$DDS_DIR/${pnr_id}.dds.json" "s3://${S3_BUCKET}/${s3_key}" \
      --content-type application/json --region "$REGION" --profile "$PROFILE"
    echo "  [5] DDS response.json -> s3://${S3_BUCKET}/${s3_key}"
  else
    echo "  [5] (dry-run) would PUT $DDS_DIR/${pnr_id}.dds.json -> s3://${S3_BUCKET}/${s3_key}"
  fi

  # 6. execution_traces pin (future processed_at so it always wins)
  echo "  [6] execution_traces INSERT (run inside rule-engine container via ECS Exec):"
  cat <<SQL
        INSERT INTO execution_traces
          (id, service_type, correlation_id, entity_id, processed_at, request_s3_key, response_s3_key)
        VALUES (gen_random_uuid(), 'DDS', 'qa-pin-${pnr}', '${pnr_id}',
                '2027-06-26 00:00:00+00', NULL, '${s3_key}');
SQL
done

echo ""
echo "=== ticket inserts (stage 4) — run after cascade settles (~30s) ==="
echo "  Use $AURORA_QUERY --env int (trip-tracer) per publish_all_fd_pnrs.sh pattern."
echo ""
echo "=== to PIN the DDS rows (stage 6), exec into the rule-engine task: ==="
cat <<'EXEC'
  TASK=$(aws ecs list-tasks --cluster ac-cct-rule-engine-platform-cluster-int \
    --profile ARC75-Temp-INT --region ca-central-1 --query 'taskArns[0]' --output text)
  aws ecs execute-command --cluster ac-cct-rule-engine-platform-cluster-int \
    --task "$TASK" --container App --interactive --profile ARC75-Temp-INT --region ca-central-1 \
    --command 'bash -c "export PGPASSWORD=\$CCT_TRACING_DB_PASSWORD; \
      psql -h \$CCT_TRACING_DB_HOST -p 5432 -d \$CCT_TRACING_DB_NAME -U \$CCT_TRACING_DB_USER -f -"'
  # then paste the 5 INSERT statements above (or pipe a base64 script per the guide).
EXEC

echo ""
echo "=== verify each (from inside VPC / via container) ==="
for pnr in "${PNRS[@]}"; do
  echo "  curl -H 'x-api-key: $DDS_API_KEY' \\"
  echo "    https://rule-engine-platform-service.ac-cct-int.cloud.aircanada.com/rule-engine/dds/output/${pnr}-${DATE}"
done

rm -rf "$TMP"
echo ""
echo "OTP/auth mailbox: Chathuranga.VirajThennakoon@aircanada.ca (all 5 PNR contacts)"
echo "Done."
